// <auto-generated />
using GeographyService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeographyService.Migrations
{
    [DbContext(typeof(GeoContext))]
    [Migration("20210603233832_updated-models")]
    partial class updatedmodels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GeographyService.Models.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("GeographyService.Models.Entities.Continent", b =>
                {
                    b.Property<int>("ContinentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.HasKey("ContinentId");

                    b.ToTable("Continents");
                });

            modelBuilder.Entity("GeographyService.Models.Entities.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.Property<int>("Surface")
                        .HasColumnType("int");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("GeographyService.Models.Entities.Mappings.CityMapping", b =>
                {
                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCapital")
                        .HasColumnType("bit");

                    b.HasKey("CityId", "CountryId");

                    b.HasIndex("CountryId");

                    b.ToTable("CityMappings");
                });

            modelBuilder.Entity("GeographyService.Models.Entities.Mappings.CountryMapping", b =>
                {
                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("ContinentId")
                        .HasColumnType("int");

                    b.HasKey("CountryId", "ContinentId");

                    b.HasIndex("ContinentId");

                    b.ToTable("CountryMappings");
                });

            modelBuilder.Entity("GeographyService.Models.Entities.Mappings.RiverMapping", b =>
                {
                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("RiverId")
                        .HasColumnType("int");

                    b.HasKey("CountryId", "RiverId");

                    b.HasIndex("RiverId");

                    b.ToTable("RiverMappings");
                });

            modelBuilder.Entity("GeographyService.Models.Entities.River", b =>
                {
                    b.Property<int>("RiverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RiverId");

                    b.ToTable("Rivers");
                });

            modelBuilder.Entity("GeographyService.Models.Entities.Mappings.CityMapping", b =>
                {
                    b.HasOne("GeographyService.Models.Entities.City", "City")
                        .WithMany("CityMappings")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeographyService.Models.Entities.Country", "Country")
                        .WithMany("CityMappings")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("GeographyService.Models.Entities.Mappings.CountryMapping", b =>
                {
                    b.HasOne("GeographyService.Models.Entities.Continent", "Continent")
                        .WithMany("CountryMappings")
                        .HasForeignKey("ContinentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeographyService.Models.Entities.Country", "Country")
                        .WithMany("CountryMappings")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Continent");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("GeographyService.Models.Entities.Mappings.RiverMapping", b =>
                {
                    b.HasOne("GeographyService.Models.Entities.Country", "Country")
                        .WithMany("RiverMappings")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeographyService.Models.Entities.River", "River")
                        .WithMany("RiverMappings")
                        .HasForeignKey("RiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("River");
                });

            modelBuilder.Entity("GeographyService.Models.Entities.City", b =>
                {
                    b.Navigation("CityMappings");
                });

            modelBuilder.Entity("GeographyService.Models.Entities.Continent", b =>
                {
                    b.Navigation("CountryMappings");
                });

            modelBuilder.Entity("GeographyService.Models.Entities.Country", b =>
                {
                    b.Navigation("CityMappings");

                    b.Navigation("CountryMappings");

                    b.Navigation("RiverMappings");
                });

            modelBuilder.Entity("GeographyService.Models.Entities.River", b =>
                {
                    b.Navigation("RiverMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
